-- CreateTable
CREATE TABLE `Vitals` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `patientId` INTEGER NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `LoC` ENUM('ALERT', 'VERBAL', 'PAIN', 'UNRESPONSIVE') NOT NULL DEFAULT 'VERBAL',
    `airwayStatus` ENUM('OPEN', 'PARTIALLY_BLOCKED', 'COMPLETELY_BLOCKED') NOT NULL DEFAULT 'OPEN',
    `breathingStatus` ENUM('NORMAL', 'SHALLOW', 'LABORED', 'ABSENT') NOT NULL DEFAULT 'NORMAL',
    `pulse` INTEGER NOT NULL,
    `pulseQuality` ENUM('REGULAR', 'IRREGULAR', 'ABSENT') NOT NULL DEFAULT 'REGULAR',
    `systolicBloodPressure` INTEGER NOT NULL,
    `diastolicBloodPressure` INTEGER NOT NULL,
    `spo2` FLOAT NOT NULL,
    `temperature` FLOAT NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `Vitals` ADD CONSTRAINT `Vitals_patientId_fkey` FOREIGN KEY (`patientId`) REFERENCES `Patient`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;
